### PR TITLE
feat: add vulnerability quick-fix + hint

### LINKED ISSUE #24: Display earliest safe version for vulnurability check
Something I noticed about the vulnurability warnings is that they only show that one exists:

Image

Since VS-Codes native npm support only shows the latest version of a package, I think it would be helpful to display the latest version in which the current vulnurability is fixed.

An example in the wild would be a project that's on Next.js `15.5.6` with the React Server Components CVE. The latest displayed version would be `16.x`, requiring developers to look up the documentation of the vulnurability to see in which version its fixed without upgrading to `16.x`. Instead, we could show that the earliest safe version is `15.5.7`.

I understand this requires some work on the npmx server side as well, so I'm not sure about feasibility at this moment. I also opened an issue in the [npmx](https://github.com/npmx-dev/npmx.dev/issues/954) repo.

wdyt?

### PR DESCRIPTION
**Pull request by nitodeco**
Closes #24 

marked 16 1 1,

This version has 1 high, 2 moderate vulnerabilities  Upgrade to 16 1 5 to

### CODE REVIEW

File: src/providers/diagnostics/rules/vulnerability.ts [hunk 1]
```diff
@@ -45,13 +91,27 @@ export const checkVulnerability: DiagnosticRule = async (dep, pkg) => {
...
+    .filter((vulnerablePackage) => vulnerablePackage.depth === 'root')
+    .flatMap((vulnerablePackage) => vulnerablePackage.vulnerabilities)
+    .map((vulnerability) => vulnerability.fixedIn)
+    .filter((fixedIn): fixedIn is string => Boolean(fixedIn))
+  const fixedInVersion = getBestFixedInVersion(rootVulnerabilitiesFixedIn)
+  const messageSuffix = fixedInVersion
+    ? ` Upgrade to ${parsed.prefix}${fixedInVersion} to fix.`
+    : ''
+  const vulnerabilityCode = fixedInVersion
+    ? `vulnerability|${fixedInVersion}`
```
Comment (9romise) [inline src/providers/diagnostics/rules/vulnerability.ts]: `Diagnostic.code.value` is user-facing in VS Code (it shows up in the Problems UI / diagnostic display). Encoding `vulnerability|<fixedInVersion>` here will likely confuse users because it looks like an implicit error code.
I’d recommend keeping it as `vulnerability` and passing the fix-version through a non-user-facing channel (or deriving it from the message) so the Quick Fix can still work without polluting the UI.

**Review by 9romise — CHANGES_REQUESTED** [review]
